#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

contactForm:
    path: /contactForm
    controller: App\Controller\HomeController::contactForm 
